### ISSUE TITLE
Error while loading the plugin

### ISSUE THREAD

**Issue by maxigaz** [sQVe/sort.nvim#2]
I've just installed sort.nvim through Packer on Neovim 0.6.0. I receive the following error message while the plugin is being loaded:

```
Error detected while processing /home/maxigaz/.config/nvim/init.test.lua:
E5113: Error while calling lua chunk: vim/shared.lua:260: after the second argument: expected table, got
nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        vim/shared.lua:260: in function 'tbl_deep_extend'
        ...vim/site/pack/packer/start/sort.nvim/lua/sort/config.lua:19: in function 'setup'
        /home/maxigaz/.config/nvim/init.test.lua:4: in main chunk
```

To reproduce it, I ran Neovim with `nvim -u ~/.config/nvim/init.test.lua --noplugin /tmp/test.txt` with the following minimal init file contents:

```
vim.cmd([[let $PLUGIN_DIRECTORY = '~/.local/share/nvim/plugtest']])
vim.cmd([[packadd sort.nvim]])

require'sort'.setup()
```

**Comment by sQVe** [comment]
Could you provide how you actually install with `packer`, since that is missing here.

**Comment by sQVe** [comment]
Ah, you need to provide an empty table to `setup`. `setup` is only needed if you want to do overrides.

If it works - please close! 👍🏼

**Comment by maxigaz** [comment]
> Could you provide how you actually install with `packer`, since that is missing here.

```lua
use {
  'sQVe/sort.nvim',
  config = function()
    require("sort").setup()
  end
}
```

> I've now made it so setup gracefully handles being called with no overrides. So, if you update it should just work.

I can confirm that there are no errors anymore. Thank you!
