### ISSUE TITLE
Sort elements inside pairs

### ISSUE THREAD

**Issue by olivertzeng** [sQVe/sort.nvim#7]
Sorting `{ a, c, b, d }` with `:Sort` if selected inside the block will be `{ a, b, c, d }`
but if the whole block is selected itll be `b, c, d }, { a`

**Comment by sQVe** [comment]
@olivertzeng This is the intended behavior. When you select the whole block it splits the input with `,`, which would give you the following blocks:
- `{ a`
- `b`
- `c`
- `d }`

Sorting these blocks alphabetically will give you `b, c, d }, { a`.

**Comment by olivertzeng** [comment]
> @olivertzeng This is the intended behavior. When you select the whole block it splits the input with `,`, which would give you the following blocks:
> 
> - `{ a`
> 
> - `b`
> 
> - `c`
> 
> - `d }`
> 
> 
> 
> Sorting these blocks alphabetically will give you `b, c, d }, { a`.
> 
> 

Yeah I was thinking that it would automatically exclude that but I should've just only select the elements from the start
Thanks though
Btw issues like this that is not intended to be fixed should be closed as "not planned won't fix" instead of completed
